name: SJSON CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake and build
      run:  cd dev && cmake -B build && cd build && make && ./sjson-dev

